site_name: Puzzle Solver API

theme:
  name: material
  features:
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - toc.follow

repo_name: giraycoskun/puzzle-solver-api

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ['src']  # search packages in the src folder

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path: ["."]

nav:
  - Home: index.md
  - Search: search.md