site_name: Puzzle Solver API

theme:
  name: material
  features:
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - toc.follow

repo_name: giraycoskun/puzzle-solver-api

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ['src']  # search packages in the src folder
          options:
            docstring_style: "google"
            show_root_heading: true
            show_if_no_docstring: true

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path: ["."]

nav:
  - Home: index.md
  - Setup: setup.md
  - Architecture: architecture.md
  - Search: search.md
  - Constrain-Satisfaction-Problem: csp.md
  - Reference: 
    - reference/reference.md
    - reference/api.md
    - reference/solver.md
    - reference/subscription.md