import os
from dotenv import load_dotenv

load_dotenv()

ENVIRONMENT = os.getenv("ENVIRONMENT")

SOLVER_WORKER_SIZE = os.getenv("SOLVER_WORKER_SIZE")

RABBITMQ_HOST = os.getenv("RABBITMQ_HOST")
RABBITMQ_PORT = os.getenv("RABBITMQ_PORT")
RABBITMQ_USER = os.getenv("RABBITMQ_USER")
RABBITMQ_PASSWORD = os.getenv("RABBITMQ_PASSWORD")
RABBITMQ_POOL_SIZE = os.getenv("RABBITMQ_POOL_SIZE")
RABBITMQ_PUZZLE_QUEUE_NAME = os.getenv("RABBITMQ_PUZZLE_QUEUE_NAME")
RABBITMQ_RESULT_QUEUE_NAME = os.getenv("RABBITMQ_RESULT_QUEUE_NAME")

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")
